version: '3'

services: 
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"

    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    restart: always 
    networks:
      - net


networks:
  net: 


