version: '3'

services: 
  jenkins:
    image: jenkins-ansible
    build: 
      context: jenkins_ansible
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    restart: always 
    networks:
      - net

  remote_host: 
    container_name: remote_host
    image: remote_host
    build:
      context: ssh_service
    restart: always
    volumes:
      - $PWD/auto.sh:/tmp/auto.sh
    networks:
      - net
  my_db:
    container_name: my_db
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes: 
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net         

  my_web:
   container_name: my_web
   image: web-server
   build:
     context: jenkins_ansible/web
   ports: 
     - "8888:80"
   networks:
     - net

  gitlab:
    container_name: gitlab_host
    hostname: gitlab.example.com
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    volumes: 
      - "$PWD/gitlab/config:/etc/gitlab"
      - "$PWD/gitlab/logs:/var/log/gitlab"
      - "$PWD/gitlab/data:/var/opt/gitlab"
    image: gitlab/gitlab-ce
    networks:
      net:


networks:
  net: 


